"""Crew Schedules: recurring channel messages backed by Hermes' own cron.

Each schedule is a real Hermes cron job (visible on the host's /cron page,
ticked by the host's own scheduler) of the cheapest possible kind: a
`no_agent` script job whose generated script posts one message into a Crew
channel through the plugin's normal routing — so a scheduled kickoff that
mentions agents starts a full relay, exactly like a human message, at zero
model cost for the trigger itself.
"""

from __future__ import annotations

import importlib
import json
import os
import re
from pathlib import Path
from typing import Any

ORIGIN = "hermes-crew"
_SCRIPT_PREFIX = "crew-schedule-"


def _hermes_home() -> Path:
    return Path(os.environ.get("HERMES_HOME", Path.home() / ".hermes"))


def _load_cron_bindings() -> Any:
    """Import Hermes cron lazily so the package stays testable in isolation."""

    jobs = importlib.import_module("cron.jobs")
    try:
        scheduler = importlib.import_module("cron.scheduler")
        notify = getattr(scheduler, "_notify_provider_jobs_changed", lambda: None)
    except Exception:  # pragma: no cover - provider notify is best-effort
        notify = lambda: None  # noqa: E731
    return jobs, notify


_SCRIPT_TEMPLATE = '''#!/usr/bin/env python3
"""Generated by Hermes Crew — posts a scheduled message into a channel.

Safe to delete; the matching schedule in Crew's Automation page owns it.
"""

import json
import sys
import time
import uuid

sys.path.insert(0, {plugin_dir!r})

PAYLOAD = json.loads({payload!r})

from hermes_crew_backend.db import CrewDatabase  # noqa: E402
from hermes_crew_backend.repositories import CrewRepository  # noqa: E402
from hermes_crew_backend.routing import Router  # noqa: E402
from hermes_crew_backend.scheduler import Scheduler  # noqa: E402

repository = CrewRepository(CrewDatabase({database!r}))
message = repository.append_message(
    PAYLOAD["channelId"],
    "user",
    PAYLOAD["content"],
    idempotency_key="schedule:%s:%d:%s" % (
        PAYLOAD["scheduleId"], int(time.time()), uuid.uuid4().hex[:6]
    ),
    mentions=PAYLOAD.get("mentions") or [],
)
scheduler = Scheduler(repository)
turns = [scheduler.enqueue(planned) for planned in Router(repository).plan(message.id)]
print(json.dumps({{
    "posted": message.id,
    "channel": PAYLOAD["channelId"],
    "turns": [turn.profile_id for turn in turns],
}}))
'''


class Schedules:
    """CRUD over Crew-owned Hermes cron jobs in the owner profile's store."""

    def __init__(self, database_path: Path, bindings: Any | None = None):
        self.database_path = Path(database_path)
        self._bindings = bindings

    @property
    def bindings(self) -> Any:
        if self._bindings is None:
            self._bindings = _load_cron_bindings()
        return self._bindings

    def _scripts_dir(self) -> Path:
        return _hermes_home() / "scripts"

    def _plugin_dir(self) -> str:
        return str(_hermes_home() / "plugins" / "hermes-crew" / "dashboard")

    def list(self) -> list[dict[str, Any]]:
        jobs, _ = self.bindings
        return [
            self._present(job)
            for job in jobs.list_jobs(include_disabled=True)
            if job.get("origin") == ORIGIN
        ]

    def create(
        self,
        *,
        name: str,
        schedule: str,
        channel_id: str,
        content: str,
        mentions: list[str],
    ) -> dict[str, Any]:
        jobs, notify = self.bindings
        # Fail early with the host's own error message for bad cadences.
        jobs.parse_schedule(schedule)

        script_id = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")[:32] or "schedule"
        scripts = self._scripts_dir()
        scripts.mkdir(parents=True, exist_ok=True)
        script_path = scripts / f"{_SCRIPT_PREFIX}{script_id}-{os.urandom(3).hex()}.py"
        payload = json.dumps(
            {
                "scheduleId": script_path.stem,
                "channelId": channel_id,
                "content": content,
                "mentions": mentions,
            },
            ensure_ascii=False,
        )
        script_path.write_text(
            _SCRIPT_TEMPLATE.format(
                plugin_dir=self._plugin_dir(),
                payload=payload,
                database=str(self.database_path),
            ),
            encoding="utf-8",
        )

        try:
            job = jobs.create_job(
                prompt="",
                schedule=schedule,
                name=f"Crew: {name}",
                deliver="local",
                origin=ORIGIN,
                script=str(script_path),
                no_agent=True,
            )
        except Exception:
            script_path.unlink(missing_ok=True)
            raise
        notify()
        return self._present(job)

    def remove(self, job_id: str) -> bool:
        jobs, notify = self.bindings
        job = jobs.get_job(job_id)
        if job is None or job.get("origin") != ORIGIN:
            raise KeyError(f"unknown crew schedule: {job_id}")
        removed = jobs.remove_job(job_id)
        script = job.get("script")
        if script and Path(script).name.startswith(_SCRIPT_PREFIX):
            Path(script).unlink(missing_ok=True)
        notify()
        return bool(removed)

    def set_paused(self, job_id: str, paused: bool) -> dict[str, Any]:
        jobs, notify = self.bindings
        job = jobs.get_job(job_id)
        if job is None or job.get("origin") != ORIGIN:
            raise KeyError(f"unknown crew schedule: {job_id}")
        updated = jobs.pause_job(job_id) if paused else jobs.resume_job(job_id)
        notify()
        return self._present(updated)

    def trigger(self, job_id: str) -> dict[str, Any]:
        jobs, notify = self.bindings
        job = jobs.get_job(job_id)
        if job is None or job.get("origin") != ORIGIN:
            raise KeyError(f"unknown crew schedule: {job_id}")
        updated = jobs.trigger_job(job_id)
        notify()
        return self._present(updated)

    @staticmethod
    def _present(job: dict[str, Any]) -> dict[str, Any]:
        script = job.get("script") or ""
        payload: dict[str, Any] = {}
        try:
            raw = Path(script).read_text(encoding="utf-8") if script else ""
            match = re.search(r"PAYLOAD = json\.loads\((.*)\)", raw)
            if match:
                payload = json.loads(eval(match.group(1)))  # noqa: S307 - our own literal
        except Exception:
            payload = {}
        return {
            "id": job.get("id"),
            "name": (job.get("name") or "").removeprefix("Crew: "),
            "schedule": (job.get("schedule") or {}).get("display")
            or job.get("schedule_display")
            or "",
            "enabled": bool(job.get("enabled", True)) and job.get("state") != "paused",
            "state": job.get("state"),
            "nextRunAt": job.get("next_run_at"),
            "lastRunAt": job.get("last_run_at"),
            "lastStatus": job.get("last_status"),
            "channelId": payload.get("channelId"),
            "content": payload.get("content"),
            "mentions": payload.get("mentions") or [],
        }
